### ISSUE TITLE
Need to support Kubernetes Secrets

### ISSUE THREAD

**Issue by HenryWelborn** [ibm-hyper-protect/k8s-operator-hpcr#16]
The VPC API key should be in a Kubernetes Secret, not a ConfigMap. Likewise the SSH configuration for OnPrem should be in a Secret.

**Comment by CarstenLeue** [comment]
https://github.com/ibm-hyper-protect/k8s-operator-hpcr/pull/17

**Comment by CarstenLeue** [comment]
done
