### ISSUE TITLE
Feedback from Playback

### ISSUE THREAD

**Issue by CarstenLeue** [ibm-hyper-protect/k8s-operator-hpcr#19]
- clarify the fact that this is only for gen2 and not gen1
- link on the readme points to gen1 documentation, this should be changed

**Comment by HenryWelborn** [comment]
@CarstenLeue can you elaborate on 
> link on the readme points to gen1 documentation, this should be changed

All of the links appear correct to me.

**Comment by CarstenLeue** [comment]
@HenryWelborn sorry for the late reply, I believe it's about the links to `https://www.ibm.com/products/hyper-protect-virtual-servers` in the main readme.
