### ISSUE TITLE
Support user defined network in domain

### ISSUE THREAD

**Issue by vishwabmc** [ibm-hyper-protect/k8s-operator-hpcr#42]
In, `resource "libvirt_domain" "notary_domain" {`

```
  # Obtain DHCP IP address on the virtual network
  network_interface {
    network_name = "default"
    wait_for_lease = true
  }
```

we have an ability to choose a default network  or  user defined network ( We can get it from virsh net )

Ref:  https://registry.terraform.io/providers/multani/libvirt/latest/docs/resources/domain#handling-network-interfaces

Adding this support would be very much beneficial as I had to use a user defined network while deploying notary and vault at a client site.
So, instead of assuming default, it would be better to have the user provide the data as needed by libvirt. The fallback can be a default network.

**Comment by CarstenLeue** [comment]
Hi @vishwabmc could you please describe the usecase a bit more. What level of network configuration do you actually need and how will the HPCR VSIs be used after they have been created by the operator?

Mirroring all options provided by libvirt for networks is probably too much for the operator, so I'd like to make sure the operator supports the intended usecase.

cc @HenryWelborn @AnbazhaganMani

**Comment by vishwabmc** [comment]
Hi @CarstenLeue I am not looking for everything that the libvirt provides. I am looking for the feature parity with : https://github.com/MetacoSA/terraform/blob/master/deployments/ibm/LinuxONE/notary/onprem/notary.tf 

Most of the things are already there in the operator, and the only thing I see needed is the ability to use the existing KVM network definition.

For example : 

Case-1 : 
  network_interface {
    network_name = "client-created"
    addresses      = ["xx.yy.zz.aa"]
  }

Case-2:
  network_interface {
    network_name = "default"
  }

Case-3:
  network_interface {
    network_name = "default"
   wait_for_leases = true
  }

At the client site, I see that they would have a KVM networking definition with the IP addresses dedicated for 
- Grep11 container
- Notary 
- Vault

In one of the client deployment, Jean-Yves had created the KVM network definition and I used the default one instead for Notary, and that really messed up the whole of the networking, and we had to re-deploy even Grep11 container.

The way I solved that was by using the KVM network definition that Jean-Yves had created.

Hopefully I answered the question.

Thanks.

**Comment by CarstenLeue** [comment]
Hi @vishwabmc thanks for the clarification, so there is no requirement to manage the network definitions via the operator, but we can assume that the network exists and we need a config setting to attach the instance to a pre-existing network.

I'll have a look into that.

After having added that, how will the KVM instances actually integrate with the other resources created by the k8s deployment?

**Comment by vishwabmc** [comment]
> so there is no requirement to manage the network definitions via the operator, but we can assume that the network exists and we need a config setting to attach the instance to a pre-existing network.

We should have the options either to (1) attach to the pre-existing network or (2) use the default one as it's done today depending on what the user prefers.

**Comment by CarstenLeue** [comment]
@AnbazhaganMani
