### ISSUE TITLE
Memory usage issue due to ssh connections not closed

### ISSUE THREAD

**Issue by iulianroman** [ibm-hyper-protect/k8s-operator-hpcr#78]
ssh connections from k8s operator to the KVM host are not closed . The amount of memory used by the ssh connections will increase until the system runs out of memory.

**Comment by iulianroman** [comment]
@CarstenLeue  I removed and recreate the deployment , but the issue persist. Can you please let me know how can i check that i run the correct version  ?

**Comment by CarstenLeue** [comment]
@iulianroman at startup of the operator it prints its version number in a string like this:
https://github.com/ibm-hyper-protect/k8s-operator-hpcr/blob/main/cli/cli.go#L50

`Starting server [VERSION]...`

**Comment by CarstenLeue** [comment]
@iulianroman looks like I called the wrong API trying to close the connection. https://github.com/ibm-hyper-protect/k8s-operator-hpcr/pull/94 fixes this. Could you please give it a try after a successful build.

**Comment by CarstenLeue** [comment]
@iulianroman could you please confirm that this issue has been fixed and then close the issue

**Comment by iulianroman** [comment]
Issue is fixed now.
